# frozen_string_literal: true

module Mcp
  module Tools
    # Mirrors GET /api/v1/sessions, GET /api/v1/sessions/search and
    # GET /api/v1/sessions/:id. An `id` short-circuits to a single session; a `query`
    # runs the same search the REST search action runs (SessionSearchable), including
    # `search_contents` for transcript text; otherwise it lists.
    #
    # That last clause is the one to keep true. This comment used to claim parity with
    # the REST search action while the call below passed one fewer argument than REST
    # did, so MCP silently had no content search at all — the one surface agents drive
    # was the one that could not search what a session actually said, and a reader who
    # trusted the comment concluded otherwise (#714).
    class QuickSearchSessions < Tool
      include SessionSearchable

      # Prompts are shown as a preview only — the full text lives in get_session.
      MAX_PROMPT_DISPLAY_LENGTH = 100
      MAX_QUERY_LENGTH = 1000

      tool_name "quick_search_sessions"

      description <<~DESC
        Search for agent sessions in Zimmer, by identity or by what was said in them.

        **Two searches, one tool.** By default `query` matches session titles plus the `metadata` and `custom_metadata` JSON — fast, and the whole corpus every time. Set `search_contents: true` to also match the session **transcript**, which is how you find a session by something said mid-conversation.

        **Checking whether a piece of work already has a session.** Search for the artifact's identifier (the tracking issue's URL or number, or the PR URL) rather than a title keyword: `query` reaches `custom_metadata`, where a spawner records the issue it handed over and where Zimmer records the PR URLs a session opens, while a title is free text, written by a spawner or generated by Zimmer. Set `show_archived: true`; finished work has archived itself, so the default excludes exactly the sessions a duplicate check most wants to find. Do not rely on the **Prompt** line in results to spot a match: it is a leading prefix of the prompt, so an identifier named later in the prompt is not shown, and `query` never reads the prompt column. The transcript, via `search_contents: true`, is the only search that reaches prompt text as such.

        **What `search_contents` costs, and what it promises.** Transcripts have no index a substring search can use, so the scan is bounded: it walks candidates newest-first, stops as soon as it has `per_page` matches or its time budget runs out, and always returns rather than timing out. It reports how far it got, and when it stopped early it returns a `scan_cursor` — pass that back to continue from exactly where it left off. Results are ordered newest-first regardless of `order`, and no total count is reported (counting matches would cost the full scan the bound exists to avoid). Narrow with `status`, `genesis` or `agent_runtime` to make it reach further back per call.

        **Use cases:**
        - Find a specific session by ID (set id parameter)
        - Search sessions by a substring of the title or the metadata/custom_metadata JSON (set query parameter)
        - Check whether an issue or PR already has a session working it (query the issue URL or number, with show_archived: true)
        - Find the session that discussed something, by a phrase from the conversation (query + search_contents: true)
        - List all sessions with an optional status filter (one status, or an array to match any)
        - Monitor sessions that need human attention (status: "needs_input")
        - Read the spot queue in the order it will be worked: `status: "waiting"`, `priority_class: "spot"`, `order: "precedence"`

        **Board visibility is NOT a scheduling signal.** Sessions carry a second, entirely separate field — `visibility`: `visible`, `hidden`, or `snoozed` until a time — whose only purpose is letting a human tidy their dashboard. It does not affect whether, when, or in what order Zimmer runs anything, and no scheduler reads it. A result marked `**Visibility:**` is running, queued and ranked exactly as it would be otherwise; the human just is not looking at its card right now. **This search is unfiltered on that axis by default, deliberately** — a session hidden from a board must never be hidden from a duplicate check — so leave `visibility` unset unless you specifically want one side of it.

        **Paused sessions.** A result carrying `**Paused:** yes` is asleep until a time somebody chose. It is
        still listed, and still holds its precedence, but Zimmer refuses to start it before its wake fires —
        a pause outranks precedence and scheduling class. Skip it and take the next candidate.

        **Returns:** A list of matching sessions with their status, configuration, and metadata. Each result's **Prompt** line is a preview: the first #{MAX_PROMPT_DISPLAY_LENGTH} characters of the prompt, then `...`. get_session has the full text.

        **Session statuses:**
        - waiting: Session created, waiting to start
        - running: Agent is actively executing
        - needs_input: The agent's turn ended and the session is idle. Agents are instructed to archive themselves when they run to completion, so a session resting here is meant to be one that needs a human — it lacked the scope or tools to finish, it is holding a PR whose merge disposition is unsettled, a human invoked it to explore or ask something, or it hit a dangerous irreversible ambiguity. Check the session transcript, since a session can also land here having simply stopped.
        - failed: Session encountered an error
        - archived: Session completed and archived
      DESC

      input_schema({
        type: "object",
        properties: {
          id: {
            type: "number",
            description: "Get a specific session by ID. When provided, other filters are ignored."
          },
          query: {
            type: "string",
            maxLength: MAX_QUERY_LENGTH,
            description: "Search query to find sessions. Substring match (case-insensitive) against the session title and the metadata/custom_metadata JSON — not against the prompt. Add search_contents: true to match transcript text too. The whole query is one substring, so several words are a PHRASE: they must appear adjacent and in that order, with no tokenising, OR-ing or stemming. Search a distinctive phrase to confirm a session said something; search one word to cast a wider net. Leave empty to list all sessions."
          },
          search_contents: {
            type: "boolean",
            description: "Also search transcript contents, not just title/metadata. Bounded and resumable: the scan walks sessions newest-first, stops at per_page matches or its time budget, forces newest-first ordering, reports no total count, and returns scan_cursor when there is more corpus left to scan. Default: false."
          },
          scan_cursor: {
            type: "string",
            description: "Resume a content search where the previous call stopped. Pass the scan_cursor from that call's output verbatim, with the same query and filters. Only meaningful with search_contents: true."
          },
          status: {
            oneOf: [
              { type: "string", enum: SessionsController::STATUS_FILTER_OPTIONS },
              { type: "array", items: { type: "string", enum: SessionsController::STATUS_FILTER_OPTIONS } }
            ],
            description: 'Filter results by status — one status, or an array of them to match any. Options: "waiting", "running", "needs_input", "failed", "archived". Mirrors the dashboard\'s multi-select status filter; omit it for every status.'
          },
          agent_runtime: {
            type: "string",
            description: "Filter results by agent runtime."
          },
          priority_class: {
            type: "string",
            enum: SessionGenesis::CLASSES,
            description: "Filter by scheduling class. \"priority\" sessions always start; \"spot\" sessions start only while a Claude Code account is under both quota targets and a session slot is free. A session's class is the one set on it, else the one its trigger stamped, else the default for its genesis — and that last case resolves live, so moving a genesis in Settings moves those sessions here immediately."
          },
          genesis: {
            type: "string",
            enum: SessionGenesis::KEYS,
            description: "Filter by genesis — where the session's line of work came from. One of: #{SessionGenesis::KEYS.join(', ')}."
          },
          order: {
            type: "string",
            enum: [ "created_desc", "precedence" ],
            description: 'Result ordering. "created_desc" (default) is newest first. "precedence" is the spot queue\'s own order — highest precedence first, oldest first within a tie — which is the order waiting spot sessions are actually started in. Precedence is an absolute scale: 100000 comes before 50.'
          },
          visibility: {
            type: "string",
            enum: [ "on_board", "off_board" ],
            description: "Filter by BOARD VISIBILITY — presentation only, and unset by default. \"on_board\" is what a tidied dashboard shows (visible, plus snoozed sessions whose snooze has run out); \"off_board\" is the hidden and snoozed ones. This says nothing about scheduling: a snoozed session runs exactly when it otherwise would. Leave it unset for duplicate checks and any other question about what work exists — filtering here can only hide sessions that do exist."
          },
          show_archived: {
            type: "boolean",
            description: "Include archived sessions in results. Default: false, which hides the highest-value duplicate-check case: a session that finished a piece of work has archived itself. A search for work that may already be done sets this true, or names \"archived\" in status, which includes them too."
          },
          page: {
            type: "number",
            minimum: 1,
            description: "Page number for pagination. Default: 1"
          },
          per_page: {
            type: "number",
            minimum: 1,
            maximum: 100,
            description: "Number of results per page (1-100). Default: 25"
          }
        },
        required: []
      })

      def call(args)
        unless args["id"].nil?
          session = find_session(args["id"])
          return "## Session Found\n\n#{format_session(session, paused: session.paused_until_scheduled_time?)}"
        end

        scope = filtered_scope(args)
        page, per_page = pagination_params(args)
        query = validated_query(args)

        if query.present? && SessionSearchable.search_contents?(args["search_contents"])
          return content_search(scope, query, per_page, args["scan_cursor"])
        end

        scope = filter_sessions_by_search(scope, query) if query.present?

        total_count = scope.count
        total_pages = (total_count.to_f / per_page).ceil
        sessions = scope.limit(per_page).offset((page - 1) * per_page)

        return "No sessions found matching the specified criteria." if sessions.empty?

        lines = [
          "## Agent Sessions",
          "",
          "Found #{total_count} session(s) (page #{page} of #{total_pages}):",
          ""
        ]

        # One batched read for the page rather than one query per row: a paused
        # session must be visibly paused in the queue listing, and the ranked
        # queue is exactly the listing a fleet-maintenance agent pages through.
        sleeping = Session.ids_paused_until_scheduled_time(sessions.map(&:id))

        sessions.each do |session|
          lines << format_session(session, paused: sleeping.include?(session.id))
          lines << ""
        end

        if page < total_pages
          lines << "---"
          lines << "*More sessions available. Use page=#{page + 1} to see the next page.*"
        end

        lines.join("\n")
      end

      private

      # The transcript-searching half. Ordered newest-first and reported with its own
      # scan footer rather than a page count, because a bounded scan cannot honestly
      # produce either a total or a stable page number — see SessionContentSearch.
      def content_search(scope, query, per_page, cursor)
        matches, scan = search_sessions_by_content(scope, query, limit: per_page, cursor: cursor)
        sessions = matches.reorder(created_at: :desc, id: :desc).to_a

        header = [ "## Agent Sessions (transcript search)", "" ]

        if sessions.empty?
          header << (scan.complete? ?
            "No sessions matched #{query.inspect} in title, metadata or transcript." :
            "No matches yet in the #{scan.scanned} most recent of #{scan.candidate_count} candidate session(s).")
          header << ""
          header << scan_footer(scan)
          return header.join("\n").strip
        end

        header << "Found #{sessions.size} match(es), newest first:"
        header << ""

        sleeping = Session.ids_paused_until_scheduled_time(sessions.map(&:id))
        sessions.each do |session|
          header << format_session(session, paused: sleeping.include?(session.id))
          header << ""
        end

        header << scan_footer(scan)
        header.join("\n").strip
      end

      def scan_footer(scan)
        lines = [ "---" ]
        if scan.complete?
          lines << "*Scan complete: all #{scan.candidate_count} session(s) matching the filters were searched. " \
                   "These are every match.*"
        else
          reason = scan.timed_out? ? "the search hit its time budget" : "the search filled its result page"
          # `scanned.positive?` matters as much as the cursor's presence: a resumed call
          # that covered nothing hands the caller's own cursor straight back, and
          # advising them to retry with it is an instruction to loop forever.
          resume = if scan.next_cursor.present? && scan.scanned.positive?
            "Continue with scan_cursor=\"#{scan.next_cursor}\" (same query and filters), or narrow the " \
            "filters so each call reaches further back."
          else
            "Nothing new was searched before the budget ran out, so there is no point to resume " \
            "from — narrow the filters (status, genesis, agent_runtime) so the scan has less to " \
            "read, then try again."
          end
          lines << "*Scan incomplete: #{scan.scanned} of #{scan.candidate_count} candidate session(s) searched, " \
                   "newest first, because #{reason}. Older sessions have NOT been ruled out. #{resume}*"
        end
        lines.join("\n")
      end

      def validated_query(args)
        query = args["query"].to_s.strip
        return "" if query.blank?
        raise ToolError, "Query too long: maximum query length is #{MAX_QUERY_LENGTH} characters" if query.length > MAX_QUERY_LENGTH

        query
      end

      def filtered_scope(args)
        # Status-summary forks are Zimmer's own bookkeeping, not sessions anyone
        # searches for — excluded here for the same reason the dashboard excludes
        # them, so the two surfaces list the same sessions.
        scope = Session.includes(:category).excluding_status_summary_forks
        scope = args["order"].to_s == "precedence" ? scope.ranked : scope.order(created_at: :desc)

        # One status or several: an array matches any of them, the way the
        # dashboard's status filter does.
        statuses = Array(args["status"]).map { |s| s.to_s.strip }.reject(&:empty?)
        if statuses.any?
          statuses.each do |status|
            unless Session.statuses.key?(status)
              raise ToolError, "Invalid status: #{status}. Valid statuses: #{Session.statuses.keys.join(', ')}"
            end
          end
          scope = scope.where(status: statuses)
        end

        scope = scope.where(agent_runtime: args["agent_runtime"]) if args["agent_runtime"].present?

        if (klass = args["priority_class"].presence)
          unless SessionGenesis::CLASSES.include?(klass)
            raise ToolError, "Invalid priority_class: #{klass}. Valid: #{SessionGenesis::CLASSES.join(', ')}"
          end
          scope = scope.priority_classified(klass)
        end

        # Board visibility: applied only when explicitly asked for. The default
        # result set is unfiltered on this axis on purpose — agents call this tool
        # to find out whether a piece of work already has a session, and a session
        # that a human snoozed off their dashboard is still very much that session.
        # Filtering it out by default would produce duplicate work with no visible
        # cause.
        case args["visibility"].to_s
        when SessionVisibility::FILTER_ON_BOARD then scope = scope.board_visible
        when SessionVisibility::FILTER_OFF_BOARD then scope = scope.board_hidden
        when "" then nil
        else
          raise ToolError, "Invalid visibility: #{args['visibility']}. Valid: #{SessionVisibility::FILTER_ON_BOARD}, #{SessionVisibility::FILTER_OFF_BOARD}."
        end

        if (genesis = args["genesis"].presence)
          unless SessionGenesis.valid?(genesis)
            raise ToolError, "Invalid genesis: #{genesis}. Valid: #{SessionGenesis::KEYS.join(', ')}"
          end
          scope = scope.with_genesis(genesis)
        end
        # Archived sessions stay out unless asked for. Naming "archived" in the status
        # filter IS asking for it — without this, `status: "archived"` and
        # `show_archived` unset would answer "no sessions found" for a filter the caller
        # spelled out, which reads as a missing session rather than a missing flag.
        unless truthy?(args["show_archived"]) || statuses.include?("archived")
          scope = scope.where.not(status: :archived)
        end

        scope
      end

      # Same clamping the REST API's paginate helper applies.
      def pagination_params(args)
        page = [ args["page"].to_i.nonzero? || 1, 1 ].max
        per_page = [ [ args["per_page"].to_i.nonzero? || 25, 1 ].max, 100 ].min
        [ page, per_page ]
      end

      def truthy?(value)
        ActiveModel::Type::Boolean.new.cast(value) == true
      end

      # Read once per call rather than once per result row — see the same note in
      # ApiSessionSerialization.
      def genesis_class_overrides
        @genesis_class_overrides ||= AppSetting.current.genesis_class_overrides || {}
      end

      # `paused` is passed in rather than derived here so the list path can answer
      # it for a whole page in one query. It is the one fact about a `waiting`
      # session that the columns cannot carry: a session somebody paused until a
      # chosen time and a session merely queued behind the quota gate are the same
      # row, and only the armed wake tells them apart.
      def format_session(session, paused: false)
        lines = [
          "### #{session.title} (ID: #{session.id})",
          "",
          "- **Status:** #{session.status}",
          "- **Agent Runtime:** #{session.agent_runtime}"
        ]

        if paused
          at = session.pending_wake_at
          when_phrase = at ? "until #{at.utc.iso8601}" : "on a pending wake-up"
          lines << "- **Paused:** yes — asleep #{when_phrase}. Zimmer will not start it before then, " \
                   "whatever its precedence or scheduling class. Skip it and take the next candidate."
        end

        # Reported only when it is not the default, and reported with the reminder
        # attached: the one way this field can do harm is an agent reading it as a
        # reason not to act on a session.
        if (tucked = session.visibility_summary)
          lines << "- **Visibility:** #{tucked} — presentation only. It does not affect scheduling or execution; " \
                   "this session runs exactly as it would if it were on the board."
        end

        lines << "- **Slug:** #{session.slug}" if session.slug.present?
        lines << "- **Genesis:** #{session.genesis_key} (#{session.priority_class(genesis_class_overrides)})"
        lines << "- **Precedence:** #{session.precedence}"
        lines << "- **Category:** #{session.category.name}" if session.category
        lines << "- **Repository:** #{session.git_root}" if session.git_root.present?
        lines << "- **Branch:** #{session.branch}" if session.branch.present?
        lines << "- **Prompt:** #{truncate_prompt(session.prompt)}" if session.prompt.present?
        lines << "- **MCP Servers:** #{session.mcp_servers.join(', ')}" if session.mcp_servers.present?
        lines << "- **Created:** #{session.created_at.iso8601}"
        lines << "- **Updated:** #{session.updated_at.iso8601}"

        lines.join("\n")
      end

      def truncate_prompt(prompt)
        return prompt if prompt.length <= MAX_PROMPT_DISPLAY_LENGTH
        "#{prompt[0, MAX_PROMPT_DISPLAY_LENGTH]}..."
      end
    end
  end
end
