# frozen_string_literal: true

module Workflow
  # The validation boundary. A workflow's payload arrives untrusted — a Slack
  # message, a webhook, a form — and is checked here, before a session exists or
  # a token is spent.
  #
  # Each workflow gets its own subclass, generated by ApplicationWorkflow.param,
  # and the subclass is strict in the three ways ActiveModel on its own is not:
  #
  #   * an UNKNOWN key is an error, not something to drop — a payload carrying a
  #     field this workflow does not declare is a payload it does not understand;
  #   * a value must already BE its declared type, or that type's unambiguous
  #     string spelling. ActiveModel would cast "abc" to 0 for an integer and to
  #     true for a boolean, and a boundary that guesses is not a boundary;
  #   * `required` means present, and for a boolean `false` counts as present.
  class Input
    include ActiveModel::Model
    include ActiveModel::Attributes

    # Raised by ApplicationWorkflow.build_input! for a payload that fails. Carries
    # the input, so a caller can render `input.errors`.
    class InvalidInputError < StandardError
      attr_reader :input

      def initialize(input)
        @input = input
        super("Invalid input for workflow #{input.class.workflow.workflow_id.inspect}: #{input.errors.full_messages.to_sentence}")
      end
    end

    # Declared type => the ActiveModel type the value is cast to once it has
    # passed the strict check. `text` is a string that wants a textarea.
    TYPES = {
      string: :string,
      text: :string,
      integer: :integer,
      boolean: :boolean,
      date: :date
    }.freeze

    # How a type reads in "must be …".
    TYPE_NOUNS = {
      string: "a string",
      text: "a string",
      integer: "an integer",
      boolean: "true or false",
      date: "a date (YYYY-MM-DD)"
    }.freeze

    INTEGER_STRING = /\A-?\d+\z/
    ISO_DATE = /\A\d{4}-\d{2}-\d{2}\z/

    # Set on each generated subclass: the workflow whose params it validates.
    class_attribute :workflow, instance_writer: false

    # Whether a raw payload value is acceptable as `type` — before any casting.
    def self.fits_type?(type, raw)
      case type
      when :string, :text then raw.is_a?(String)
      when :integer then raw.is_a?(Integer) || (raw.is_a?(String) && INTEGER_STRING.match?(raw))
      when :boolean then [ true, false, "true", "false" ].include?(raw)
      when :date then raw.instance_of?(Date) || iso_date?(raw)
      else false
      end
    end

    def self.iso_date?(raw)
      raw.is_a?(String) && ISO_DATE.match?(raw) && Date.valid_date?(*raw.split("-").map(&:to_i))
    end

    # The generated subclasses are anonymous, and ActiveModel reads a model name
    # to build every error message.
    def self.model_name
      ActiveModel::Name.new(self, nil, "Input")
    end

    validate :no_unknown_keys
    validate :values_match_declared_params

    # @param payload [Hash] string or symbol keys
    def initialize(payload = {})
      raise ArgumentError, "a workflow payload is a Hash, not #{payload.class}" unless payload.is_a?(Hash)

      payload = payload.stringify_keys
      @unknown_keys = payload.keys - self.class.attribute_names
      @raw_values = payload.slice(*self.class.attribute_names)
      super(@raw_values)
    end

    # The validated input as a WorkflowRun records it: every declared param, cast,
    # nil where an optional one was not supplied — and as JSON, so a date is its
    # "YYYY-MM-DD" string here exactly as it is once it comes back out of jsonb.
    # The typed values are the readers (`input.for_date`), which #plan uses.
    def to_h
      attributes.as_json
    end

    private

    def no_unknown_keys
      return if @unknown_keys.empty?

      errors.add(:base, "unknown #{'parameter'.pluralize(@unknown_keys.size)}: #{@unknown_keys.sort.join(', ')}")
    end

    def values_match_declared_params
      workflow.params.each do |param|
        raw = @raw_values[param.key.to_s]

        if raw.nil? || (raw.is_a?(String) && raw.strip.empty?)
          errors.add(param.key, :blank) if param.required
        elsif !self.class.fits_type?(param.type, raw)
          errors.add(param.key, "must be #{TYPE_NOUNS.fetch(param.type)}")
        elsif param.options && !param.options.include?(public_send(param.key))
          errors.add(param.key, :inclusion, value: raw)
        end
      end
    end
  end
end
