require "active_support/core_ext/integer/time"

# Set Redis URL for development
ENV["REDIS_URL"] ||= "redis://localhost:6379"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In development, use the in-repo air.json so local edits are picked up without
  # needing a ~/.air/air.json file.
  config.air_json_path = Rails.root.join("air.json").expand_path.to_s

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use Redis cache store in development (database 1 to avoid conflict with other apps)
  config.cache_store = :redis_cache_store, { url: "#{ENV["REDIS_URL"]}/1" }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # GoodJob configuration for development
  # Use :async mode for development - runs jobs in separate threads within the Rails process
  config.good_job.execution_mode = ConnectionBudget.execution_mode

  # Queue configuration matching production for dev/prod parity (configurable via ENV):
  # - agents: Long-running AgentSessionJob instances
  # - pollers: Singleton polling jobs
  # - triggers: Latency-sensitive trigger firing (AoEventTriggerJob,
  #     ScheduleTriggerJob) — isolated so wakes aren't starved by the `default`
  #     queue's periodic/bulk backlog.
  # - default: Everything else
  #
  # From ConnectionBudget, which also sizes the pool in database.yml. In :async these
  # threads run inside the web process, so that pool covers Puma AND GoodJob.
  config.good_job.queues = ConnectionBudget.good_job_queues
  config.good_job.max_threads = ConnectionBudget.good_job_max_threads
  config.good_job.poll_interval = 5
  config.good_job.enable_cron = true
  # Resolved from config/cron_schedule.rb, the single source for all three environments.
  # Development runs a deliberate subset; each omission is declared on the entry there.
  config.good_job.cron = CronSchedule.for(:development)

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Allow ngrok URLs for development tunneling
  config.hosts << /[a-z0-9-]+\.ngrok-free\.app/
  config.hosts << /[a-z0-9-]+\.ngrok\.app/
  config.hosts << /[a-z0-9-]+\.ngrok\.io/

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # GoodJob dashboard configuration
  config.good_job.enable_dashboard = true
end
